### ISSUE TITLE
How to produce create 3D plots

### ISSUE THREAD

**Issue by ubuntuslave** [DavidPowell/openmodes-examples#1]
Hello, Dr. Powell.

This is not really an issue, but a question on how you achieve running your Jupyter (iPython) notebooks from a different repo (instead of the actual [OpenModes](https://github.com/DavidPowell/OpenModes) repo where the `openmodes` packages is found. I don't think Github or nbviewer have `openmodules` as an installed package by default.  I tried forking your `OpenModes` repo and moving the `.ipynb` examples from [openmodes-examples](https://github.com/DavidPowell/openmodes-examples) without success.

I'm attempting to reproduce your `init_3d()` webgl rendering for my own 3D visualizations (just started looking into your approach of visualizing 3D plots with webgl on iPython notebooks), so please forgive my lack of understanding on this subject.

Thanks for any hints you may be able to provide!

**Comment by DavidPowell** [comment]
You might have success by moving the example notebook files to the root of the Openmodes folder, but I haven't tried this.

These examples are based on the assumption that the OpenModes package is installed globally, as per the [installation instructions](http://openmodes.readthedocs.org/en/latest/install.html).

If you've downloaded the source from git, then instead of installing with `pip`, you should just run `python setup.py install`, however this does require that you have a fortran compiler installed. For this reason I provide pre-compiled windows binaries (which are installed by pip), although I hope that the installation is relatively painless under Linux if all the right packages are installed.

There is also a [docker image](https://hub.docker.com/r/davidpowell/openmodes/) that includes the examples. This is a fairly easy way to get OpenModes running, at least if you are already familiar with docker.

Edit: note that the examples are aimed at the latest release of OpenModes, and currently will not work with the git master version

**Comment by ubuntuslave** [comment]
Thanks for the quick response. My actual concern is: how does github assume the availability of openmodes for the examples. I don't see openmodes on the root of the repository for the examples, but the notebooks still seem to find openmodes online somehow. Are these notebooks pregenerated somehow? I'm new to the idea of running notebooks directly on github.

**Comment by DavidPowell** [comment]
Github (or nbviewer.ipython.org which often gives better results) does not run the notebooks, it just displays the output which was stored in the notebook the last time it was run.

With regards to the 3D plots, the call `init_3d()` injects javascript into the output of the notebook using IPython's `display` function, so it gets saved along with all other output, including the 3D plots themselves.

**Comment by ubuntuslave** [comment]
Great! You have answered my question! Thank you very much!
